// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spjcjjbnfbjycsxgtbpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwamNqamJuZmJqeWNzeGd0YnB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2ODEyODEsImV4cCI6MjA3MDI1NzI4MX0.zokUi6GV6rXvqq2chrRRboYtli2O1vQvzG10Rz4f5sk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});